###
POST http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "123456"
}

###
POST http://localhost:8080/auth/register HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "123456"
}

###
POST http://localhost:8080/auth/refresh-token HTTP/1.1


GET http://localhost:8080/test-error HTTP/1.1

###
GET http://localhost:8080/auth/get-all HTTP/1.1
